import { StyleSheet } from "react-native";
import { colors, spacing, borderRadius } from "@/lib/theme";

export const mvpRecapStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  cardContainer: {
    width: "90%",
    maxWidth: 400,
    maxHeight: "80%",
  },
  card: {
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  trophyContainer: {
    marginBottom: spacing.md,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: spacing.lg,
    textAlign: "center",
  },
  winnerSection: {
    alignItems: "center",
    marginBottom: spacing.lg,
    backgroundColor: "rgba(255,255,255,0.2)",
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    width: "100%",
  },
  winnerName: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: spacing.xs,
    textAlign: "center",
  },
  beerCount: {
    fontSize: 20,
    color: "#FFF",
    fontWeight: "600",
  },
  eventInfo: {
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  eventName: {
    fontSize: 16,
    color: "#FFF",
    fontWeight: "600",
    marginBottom: spacing.xs / 2,
    textAlign: "center",
  },
  date: {
    fontSize: 14,
    color: "rgba(255,255,255,0.8)",
  },
  leaderboardContainer: {
    width: "100%",
    maxHeight: 200,
  },
  leaderboard: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  leaderboardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  rank: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFF",
    width: 30,
  },
  playerName: {
    flex: 1,
    fontSize: 16,
    color: "#FFF",
  },
  playerCount: {
    fontSize: 16,
    color: "#FFF",
    fontWeight: "600",
  },
  actions: {
    flexDirection: "row",
    gap: spacing.md,
    width: "100%",
  },
  shareButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.3)",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
  },
  shareText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  closeButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
  },
  closeText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
